version = 1

test_patterns = [
  "tests/**",
  "**/**_test.go"
]

exclude_patterns = [
  "migrations/**",
  "node_modules/**"
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/QuackatronHQ/demo-go"